// Full Pharco product portfolio:used by /products-overview and /product-detail
export type Product = { n: string; ta: string };

const make = (names: string[], ta: string): Product[] => names.map((n) => ({ n, ta }));

export const PRODUCTS: Product[] = [
  ...make(["ADOLOR","KETOTIPHARCO","ALGASON","LIDOCAINE","BROMHEXINE","MELOXICAM","BUCCAZOLE","MICOBAN","CETRAK","MICROSERC","DECLOPHEN","OPLEX","DECLOPHEN-FAST","OPLEX-N","DEPOFORT-B12","OPLEX-N PLUS","DEPOVIT","OTOCALM","DEXAMETHASONE","PARACETAMOL","DEXAPHEN","PARAGESIC","EUROCOX","PROFUSOL","FARCOCAINE","RADIAN","FARCOLIN","RECTOPLEXIL","FARCOSOLVIN","RESPIRIN","FASTEL","RINOSIN","FENAC","SEDATUSS","FLASH-ACT","SINE-UP","FLEXOFAN","TERHEXINE","FLUCALM","TORMEEL","GC-MOL","URICOL","HISTAZINE-1","URICONTROL","HOSTAPRED","URINEX","HYDRAL","XILONE","INJECTMOL","XILONE-FORTE","KETOFAN","ZACAGLONE","KETOLAC"], "Primary Care"),
  ...make(["AMEROPEM","CLAVIMOX","AMFLUX","CLUDINETECH","AMPIFLUX","CURISAFE","AMRIZOLE","DAKTAVIRA","AZROLID","ERTAPENEM","CEFACLOR","EUROZOLE","CEFAXONE","GRATISOVIR","CEFAZONE","IMPLATINZE","CEFAZONE PLUS","LARIVEX","CEFEPIME","LEVOTAVIN","CEFIXIME","NIFUNAL","CEFORAN","SULBIN","CEFZIM","TIGEPHARCO","CIPROFAR","ULTRAMOX","CIPROFLOXACIN","ZINOL","CLARITHRO"], "Antimicrobial"),
  ...make(["AMLODIPINE","DUVADILAN","ASPRICARLO","FARCODARONE","BISOLOCK","FARCOPRIL-PLUS","CANDEBLOCK","HYSARTAN","CANDEBLOCK-D","LINADIABET","CONTROPACE","VASONORM","DEXIGLOFOZIN"], "Cardiometabolic"),
  ...make(["ALVERINSPASM","GASTRAZOLE","AMRASE","GLYCERIN","BILICHOL","LUBICONT","BILURON","MIOPAN","BISADYL","ORNITATE","COLOMINT","PERLOC","DIGESTIN","RANI-F","ESTOHALT","SIMETHICONE","FAWAR-COLA","SPASMO-AMRASE","FAWAR-FAWAKEH","SPASMODIGESTIN","FAWAR-FRUIT","SPASMOFEN","FAWAR-LEMON","SPASMOTALIN","FARCOTILIUM","ZINC","FAWAR-C","ZINCORHEA"], "GIT"),
  ...make(["AEROTROPA","NORHINOSE","BUDELIZER","SPIRIVA","BUDEXAN","THEOPHYLLINE","FORBUDES","TICANASE","METROHALER","TICANASE PLUS","MONTEKAL","WINDY","NASOFLUTIN"], "Respiratory"),
  ...make(["BORTEZOMIB","LETROZOL","DASATINIB SYNTHON","NATIRAN","LENALIDOMIDE","TAMOXIFEN"], "Oncology"),
  ...make(["BIPERIDEN","NERVALTA","CEREBROCETAM","RAPIZAPINE","ESCITA","SHANCITA","NEOSTIGMINE"], "CNS"),
  ...make(["BETAMETHASONE","DERMATIN","BETAPANTHEN","DEXPANTHENOL","CLINDA-SOL","FARCOCIN","CLOSOL","POLYDERM","CLOVACORT","TOPICORT"], "Dermatology"),
  ...make(["ALFABRIMO","OPTIGUARD","DORZOLAMOL","PHARMA TEARS","EYE-CLEAR","PHARMAPRED EYEDROPS","FARCOBRASONE","PHARMASTIN","HYALOPTIC","PHENAMIDE-P","OPHTASTAT"], "Ophthalmology"),
  ...make(["ANASTROZOLE","OVIUNHIPTA","FEMOGESAL","PROGEST","FOLICAP","TECHNORRIN","GYNOZOL","TECHNOSPIRON","MARTAVIVA","TECHNOVULA","NORGESTADIOL","TONADOGEST","NOROCARMENA","TREXZOLA"], "Women's Health"),
  ...make(["AMRI-K","FERRO-6","BARAKA","HAEMOJET","CALMSEEF","HAEMOPOWER","C-SAFE","HEPAFORT","DECAL B12-N","NEUROVIT","DECAL-B12","NEW-GELTA","DIET-SWEET","NOVOCOBAL","DOPPELHERZ ACTIVE-IRON","OMEGA-3-SAFE","DOPPELHERZ ACTIVE-MAG-KAL","OMEGASEEF","DOPPELHERZ ACTIVE-MENO","ROSASEEF","DOPPELHERZ ACTIVE-PURE-3","ROYAL-JELLY","DOPPELHERZ ACTIVE-VITAL MATERNAL PLUS","VITAMIN A","EASY-SLIM","VITAMIN E","EURONEMIA","ZINCOSAFE","FARCOVIT-B12"], "Vitamins & Supplements"),
  ...make(["ALAMBUPHINE","ANAHAL"], "Anaesthesia"),
];

export const TA_TABS = [
  "Primary Care","Antimicrobial","Cardiometabolic","Respiratory","Oncology",
  "GIT","CNS","Dermatology","Ophthalmology","Women's Health",
  "Vitamins & Supplements","Anaesthesia",
];
