export type contactPageResources = {
  fillTheForm: string;
  Home: string;
  Name: string;
  Email: string;
  Subject: string;
  Message: string;
  Submit: string;
  successfullySubmitted: string;
  isRequired: string;
  enterYour: string;
  requiredCaptcha: string;
  contactUs: string;
};
export type footerResources = {
  contactUs: string;
  Brands: string;
  InvestorRelations: string;
  Newsroom: string;
  aboutUs: string;
  FollowUs: string;
  ExploreFG: string;
  OtherLinks: string;
  joinOurNewsLetter: string;
  enterYour: string;
  Subject: string;
  Subscribe: string;
  emailAlreadySubscribed: string;
  subscribedSuccessfully: string;
  invalidEmail: string;
  Email: string;
  isRequired: string;
  allRightsReserved: string;
  GetInTouch: string;
  PSdigital: string;
};
export type headerResources = {
  contactUs: string;
  menu: string;
  Promotions: string;
  Catering: string;
  locations: string;
  aboutUs: string;
};
export type contactInfoResources = {
  IframeSrc: string;
  DirectionSrc: string;
  ID: string;
  DisplayOrder: string;
  Status: boolean;
  IsMain: boolean;
  Address: string;
  Branch: string;
  Project: string;
  Phone1: string;
  Phone2: string;
  Phone3: string;
  Email1: string;
  Email2: string;
  Email3: string;
  URL1: string;
  URL2: string;
  URL3: string;
  POX: string;
  Zooming: string;
  Longitude: string;
  Latitude: string;
  AddressLine2: string;
  State: string;
  Region: string;
  City: string;
  Area: string;
};
